name: Deploy Frontend and Backend

on:
  push:
    branches:
      - test-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies and run setup-start script
      run: |
        npm run setup-start
      env:
        CI: false

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        export_default_credentials: true

    - name: Generate SSH Key
      run: |
        mkdir -p ~/.ssh
        ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
        echo "Host *" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config

    - name: Add SSH key to the agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy frontend
      run: |
        gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} --zone ${{ secrets.GCP_ZONE }} --command "sudo rm -rf /var/www/html/*"
        gcloud compute scp --recurse client/build/* ${{ secrets.GCP_INSTANCE_NAME }}:/var/www/html/ --zone ${{ secrets.GCP_ZONE }}

    - name: Deploy backend
      run: |
        gcloud compute scp --recurse * ${{ secrets.GCP_INSTANCE_NAME }}:/path/to/backend/ --zone ${{ secrets.GCP_ZONE }}
        gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} --zone ${{ secrets.GCP_ZONE }} --command "cd /path/to/backend && npm install && pm2 restart all"

    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: build-logs
        path: |
          client/build.log
          backend/build.log