name: Deploy Frontend and Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies and build frontend
      working-directory: ./client
      run: |
        npm install
        npm run build
      env:
        CI: false

    - name: Install dependencies and build backend
      run: |
        npm install
        npm start

    - name: Add SSH key to the agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy frontend
      run: |
        scp -o StrictHostKeyChecking=no -r client/build/* ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/html/

    - name: Deploy backend
      run: |
        scp -o StrictHostKeyChecking=no -r * ${{ secrets.USER }}@${{ secrets.HOST }}:/path/to/backend/
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} 'cd /path/to/backend && npm install && pm2 restart all'

    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: build-logs
        path: |
          client/build.log
          backend/build.log