name: Deploy Frontend and Backend

on:
  push:
    branches:
      - test-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        export_default_credentials: true

    - name: Add SSH key to the agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Copy repository to GCP instance
      run: |
        gcloud compute scp --recurse . ${{ secrets.GCP_INSTANCE_NAME }}:/home/deploy/repo --zone ${{ secrets.GCP_ZONE }}

    - name: Build and deploy on GCP instance
      run: |
        gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} --zone ${{ secrets.GCP_ZONE }} --command "
          cd /home/deploy/repo &&
          npm install &&
          npm run setup-start &&
          sudo rm -rf /var/www/html/* &&
          sudo cp -r client/build/* /var/www/html/
        "